name: healthguard
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter

  record: ^5.0.0
  audioplayers: ^6.0.0
  path_provider: ^2.1.0

  runanywhere: ^0.15.11
  runanywhere_llamacpp: ^0.15.11
  runanywhere_onnx: ^0.15.11

dependency_overrides:
  record_linux: ^1.0.0
